### ISSUE TITLE
NullReferenceException when app event subscription is missing sourceFilter

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-events#351]
Manged to produce a 500 error with the following POST request:
```
{
  "endpoint": "https://webhook.site/3666a820-a551-49c4-abeb-f5b1c8e7d59a",
  "resourceFilter": "urn:altinn:resource:altinnapp.ttd.apps-test"
}
```
StackTrace snippet:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Altinn.Platform.Events.Services.AppSubscriptionService.ValidateSubscription(Subscription eventsSubscription, String& message) in /Events/Services/AppSubscriptionService.cs:line 143
   at Altinn.Platform.Events.Services.AppSubscriptionService.CreateSubscription(Subscription eventsSubscription) in /Events/Services/AppSubscriptionService.cs:line 85
```

**Comment by acn-sbuad** [comment]
Validated in at22. With provided request body error message `"A valid app id is required in Source filter {environment}/{org}/{app}"` is returned
